### ISSUE TITLE
`macos-arm64-*` fails with `Failed to install qpdf`

### ISSUE THREAD

**Issue by pawelru** [r-hub/actions#29] opened 2024-11-25 09:50 UTC
[Example](https://github.com/insightsengineering/roxy.shinylive/actions/runs/11992913650)

failed pipelines:
- R-hub 🌐 / macos-arm64 (r-release-macos-arm64) (R-release)
- R-hub 🌐 / macos-arm64 (r-oldrel-macos-arm64) (R-oldrel)

`r-hub/actions/setup-r@v1`  -->  `Downloading macOS utils`:
```
Error: Failed to get R release: Failed to get R 4.4.2: Failed to install qpdf: Error: The process '/opt/homebrew/bin/brew' failed with exit code 1
```

Appreciate your help on this!

**Comment by gaborcsardi** [comment] 2024-11-25 10:07
Duplicate of https://github.com/r-lib/actions/issues/948, should be fixed.

**Comment by pawelru** [comment] 2024-11-25 10:16
OK sorry about this - I should have checked this before. Then please feel free to close it

**Comment by gaborcsardi** [comment] 2024-11-25 10:25
Can you try to re-run, to make sure that it works?

**Comment by pawelru** [comment] 2024-11-25 10:28
All looks good!
```
Downloading macOS utils
  /opt/homebrew/bin/brew unlink pkg-config@0.29.2
  Unlinking /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3... 4 symlinks removed.
  /opt/homebrew/bin/brew install qpdf pkgconfig checkbashisms ghostscript
  ==> Downloading https://ghcr.io/v2/homebrew/core/qpdf/manifests/11.9.1
  ==> Fetching qpdf
  ==> Downloading https://ghcr.io/v2/homebrew/core/qpdf/blobs/sha256:a4aa3f1a655448[61](https://github.com/insightsengineering/roxy.shinylive/actions/runs/11992913650/job/33469840530#step:4:64)debcfbf6c5df9283e17e4a2f40b14b8c680fa9e8[63](https://github.com/insightsengineering/roxy.shinylive/actions/runs/11992913650/job/33469840530#step:4:66)6c0ae9
  ==> Downloading https://ghcr.io/v2/homebrew/core/pkgconf/manifests/2.3.0_1
(...)
```

**Closed as completed** 2024-11-25 10:37 UTC
